-- =====================================================================
-- TOTVS Hermes - DDL do schema Oracle
-- =====================================================================
-- Gerado a partir do mapeamento JPA (Hibernate schema-generation) para
-- Oracle Database 19c. A aplicacao cria/atualiza o schema sozinha com
-- spring.jpa.hibernate.ddl-auto=update; este script serve como
-- documentacao e para criar o schema manualmente quando necessario.
--
-- Observacoes de portabilidade:
--   * textos longos (transcricoes, resumos da analise) usam CLOB;
--   * campos usados na pesquisa textual sao VARCHAR2, porque o Oracle
--     nao aceita LOWER() sobre CLOB;
--   * chaves primarias usam IDENTITY (Oracle 12c+);
--   * booleanos sao NUMBER(1) com CHECK (0,1).
-- =====================================================================

create table clientes (nota_nps float(53), uf varchar2(2 char), data_atualizacao timestamp(6), data_cadastro timestamp(6) not null, id number(19,0) generated as identity, cnpj varchar2(14 char) not null, status varchar2(20 char) not null check (status in ('PROSPECT','ATIVO','EM_RISCO','INATIVO')), telefone_contato varchar2(20 char), faixa_faturamento varchar2(60 char), cidade varchar2(80 char), segmento varchar2(80 char), contato_principal varchar2(120 char), email_contato varchar2(150 char), nome_fantasia varchar2(150 char), razao_social varchar2(150 char) not null, observacoes clob, primary key (id), constraint uk_cliente_cnpj unique (cnpj));
create table comentarios_reuniao (editado number(1,0) not null check (editado in (0,1)), autor_id number(19,0) not null, data_atualizacao timestamp(6), data_criacao timestamp(6) not null, id number(19,0) generated as identity, reuniao_id number(19,0) not null, texto clob not null, primary key (id));
create table feedbacks_reuniao (id number(19,0) generated as identity, reuniao_id number(19,0) unique, categoria_problema varchar2(255 char), nivel_criticidade varchar2(255 char) check (nivel_criticidade in ('ALTA','MEDIA','BAIXA')), acao_de_melhoria clob, como_identificar_antes clob, mensagem_educativa clob, motivo_nao_identificado_antes clob, perguntas_recomendadas clob, problema_identificado clob, sinais_na_conversa clob, primary key (id));
create table importacao_lotes (total_registros_brutos number(10,0) not null, total_reunioes_com_erro number(10,0) not null, total_reunioes_duplicadas number(10,0) not null, total_reunioes_incompletas number(10,0) not null, total_reunioes_validas number(10,0) not null, data_hora_importacao timestamp(6) not null, id number(19,0) generated as identity, codigo_lote varchar2(255 char) not null unique, hash_arquivo varchar2(255 char), nome_arquivo_original varchar2(255 char), status_processamento varchar2(255 char), observacoes clob, primary key (id));
create table insights (confianca number(10,0), id number(19,0) generated as identity, reuniao_id number(19,0), prioridade varchar2(255 char), tipo varchar2(255 char), descricao clob, trecho_origem clob, primary key (id));
create table planos_acao (prazo date not null, data_atualizacao timestamp(6), data_conclusao timestamp(6), data_criacao timestamp(6) not null, id number(19,0) generated as identity, responsavel_id number(19,0) not null, reuniao_id number(19,0) not null, prioridade varchar2(20 char) not null check (prioridade in ('ALTA','MEDIA','BAIXA')), status varchar2(20 char) not null check (status in ('PENDENTE','EM_ANDAMENTO','CONCLUIDO','CANCELADO')), titulo varchar2(120 char) not null, descricao varchar2(2000 char), resultado clob, primary key (id));
create table reunioes (analisada number(1,0) check (analisada in (0,1)), data date, dt_ultima_pesquisa date, duplicada number(1,0) check (duplicada in (0,1)), duracao_minutos number(10,0), flg_externo number(1,0) check (flg_externo in (0,1)), nota_nps float(53), pontuacao_completude number(10,0), quantidade_locutores number(10,0), quantidade_palavras number(10,0), score_comercial number(10,0), score_qualidade number(10,0), cliente_id number(19,0), data_importacao timestamp(6), id number(19,0) generated as identity, id_reuniao_original_duplicada number(19,0), lote_id number(19,0), tema_reuniao varchar2(500 char), resumo_reuniao varchar2(1000 char), areas_internas varchar2(255 char), budget_identificado varchar2(255 char), categoria_reuniao varchar2(255 char), categorias_principais varchar2(255 char), cliente varchar2(255 char), cnae varchar2(255 char), concorrentes_identificados varchar2(255 char), duracao_formatada varchar2(255 char), empresas_identificadas varchar2(255 char), faturamento varchar2(255 char), formato varchar2(255 char), hash_reuniao varchar2(255 char), id_externo varchar2(255 char), motivo_duplicidade varchar2(255 char), nome_arquivo_origem varchar2(255 char), nome_unidade varchar2(255 char), personas_identificadas varchar2(255 char), prioridade varchar2(255 char), produtos_identificados varchar2(255 char), risco_churn varchar2(255 char) check (risco_churn in ('ALTO','MEDIO','BAIXO')), segmento varchar2(255 char), sentimento varchar2(255 char) check (sentimento in ('POSITIVO','NEGATIVO','CRITICO','MISTO','OPORTUNIDADE_COMERCIAL','NEUTRO')), status_completude varchar2(255 char) check (status_completude in ('COMPLETA','PARCIAL','INCOMPLETA')), status_meeting_original varchar2(255 char), tp_recurso varchar2(255 char), uf varchar2(255 char), vendedor varchar2(255 char), dores_identificadas clob, feedback_educativo clob, insight_parcial clob, insights_json clob, locutores_identificados clob, motivo_incompletude clob, oportunidades clob, pontos_principais clob, recomendacao_final clob, sentimento_justificativa clob, transcricao_original clob, transcricao_tratada clob, primary key (id));
create table usuarios (ativo number(1,0) not null check (ativo in (0,1)), data_atualizacao timestamp(6), data_cadastro timestamp(6) not null, id number(19,0) generated as identity, perfil varchar2(20 char) not null check (perfil in ('ADMIN','GESTOR','VENDEDOR','ANALISTA')), cargo varchar2(30 char), senha_hash varchar2(100 char) not null, nome varchar2(120 char) not null, email varchar2(150 char) not null, primary key (id), constraint uk_usuario_email unique (email));
alter table comentarios_reuniao add constraint FKr3kuybe0s3xjjh361x2bugjvi foreign key (autor_id) references usuarios;
alter table comentarios_reuniao add constraint FKewr8rwhaaeip5nlhxgx064h4 foreign key (reuniao_id) references reunioes;
alter table feedbacks_reuniao add constraint FKqo0v8yu56c57t75uly21y4rro foreign key (reuniao_id) references reunioes;
alter table insights add constraint FKpk7thect4bgllop27fm9barj6 foreign key (reuniao_id) references reunioes;
alter table planos_acao add constraint FKlodpv05p8t6v0nroj5gn6bysa foreign key (responsavel_id) references usuarios;
alter table planos_acao add constraint FK2u3s9apet6wqg015h15o1atr8 foreign key (reuniao_id) references reunioes;
alter table reunioes add constraint FK9wttnl80krobsgs76rybeshbc foreign key (cliente_id) references clientes;
alter table reunioes add constraint FKr14ni8q54jhp7gucbqa4riugn foreign key (lote_id) references importacao_lotes;
